### ISSUE TITLE
  File "/usr/local/bin/bitbucket-sync", line 5, in <module>     from pkg_resources import load_entry_point

### ISSUE THREAD

**Issue by pixelschubseAtWork** [Gautier/bitbucket-sync#10]
hi out there
we're using lots of bitbucket repos in my company so was really happy when i found your script. I've no clue what's the problem. When i execute your script i get the following error:

bitbucket-sync
Traceback (most recent call last):
  File "/usr/local/bin/bitbucket-sync", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests>=2.0.0

am i using wrong python version or smth. sm? i've never been in touch with python - can you please give me an advice?

**Comment by Gautier** [comment]
Hi,

this issue sounds similar to this one on a different project : https://github.com/jakubroztocil/httpie/issues/148

The workaround is to upgrade setuptools with 

    pip install --upgrade setuptools

Let me know if this does the trick.

Best,
Gautier
