### ISSUE TITLE
AttributeError: 'module' object has no attribute 'check_output' 

### ISSUE THREAD

**Issue by beeman** [Gautier/bitbucket-sync#11]
I'm trying to backup all the repositories of my organization, so I've created and OAuth key with that account. Now when I try to run the backup I get the following error.

Any clues on how to fix this?

```
bitbucket-sync --key MyOrgranizationKey --secret MyOrganizationSecret --directory .
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.6/site-packages/bitbucket_sync/main.py", line 109, in worker
    if sync_repo(directory, repo, lock):
  File "/usr/lib/python2.6/site-packages/bitbucket_sync/main.py", line 83, in sync_repo
    scm.validate_local_repository()
  File "/usr/lib/python2.6/site-packages/bitbucket_sync/main.py", line 40, in validate_local_repository
    subprocess.check_output(
AttributeError: 'module' object has no attribute 'check_output'
```

**Comment by Gautier** [comment]
Hi Bram,

With your message I just realise that bitbucket-sync is only compatible with Python 2.7.

For my own curiosity, what system are you using?

Best,
Gautier

**Comment by beeman** [comment]
Hi @Gautier, thanks for your prompt reply.

This machine is running Red Hat Enterprise Linux Server release 6.6 which is indeed running Python 2.6.

I'll try in on a RHEL7 machine! Thanks!
